#ifndef TIDEGAUGE_RUNTIME_CONFIG_H
#define TIDEGAUGE_RUNTIME_CONFIG_H
#ifndef TIDEGAUGE_WATCHDOG_TIMEOUT_MS
#define TIDEGAUGE_WATCHDOG_TIMEOUT_MS 8000U
#endif
static_assert(TIDEGAUGE_WATCHDOG_TIMEOUT_MS >= 1000 && TIDEGAUGE_WATCHDOG_TIMEOUT_MS <= 8388,
              "RP2040 watchdog timeout must be between 1000 and 8388 ms");
#ifndef TIDEGAUGE_MIN_DISTANCE_M
#define TIDEGAUGE_MIN_DISTANCE_M 0.02f
#endif
#ifndef TIDEGAUGE_MAX_DISTANCE_M
#define TIDEGAUGE_MAX_DISTANCE_M 6.0f
#endif
#endif
